
image: Visual Studio 2019

environment:
  
  matrix:
  - solution_path: Book/Task1/Task1.sln
  - solution_path: Book/Task3/Task3.sln
  - solution_path: Lanit/Homework1/Homework1.sln
  
before_build:
  - nuget restore %solution_path%

build_script:
- msbuild %solution_path%